# Generated by Django 6.0 on 2026-01-16 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_taxofficerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('return_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assessment_year', models.CharField(max_length=9)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('filing_date', models.DateField(auto_now_add=True)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_returns', to='users.taxofficerprofile')),
                ('tax_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='users.taxcategory')),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_returns', to='users.taxpayerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('tax_return', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='taxes.taxreturn')),
            ],
        ),
    ]
